mujoco_simulator:
    
    # 电机状态与命令topic
    lowStateTopic: "/low_state" 
    jointCommandsTopic: "/low_command"
    imu2Topic: "/secondary_imu/converted"
    odomTopic: "/robot_odom"  # 里程计信息topic 

    # 里程计发布频率
    odomPublishRate: 100.0  # Hz，里程计信息发布频率
    # 点云发布频率
    pointCloudPublishRate: 10.0  # Hz，点云信息发布频率
    # 低状态发布频率
    lowStatePublishRate: 100.0  # Hz，电机与IMU状态发布频率
    # 渲染频率
    renderRate: 60.0  # Hz，MuJoCo可视化窗口渲染频率

    # 消息延迟
    cmdDelay: 0 # 单位是次,0是没有延迟, 当控制器为50Hz时，一个单位是20ms
    stateDelay: 0 # 单位是次,0是没有延迟, 当仿真频率为500Hz时，一个单位是2ms
    # 传感器噪声
    noise_imu_angle_acc: 0.0
    noise_imu_gravity: 0.0 
    noise_joint_pos: 0.0
    noise_joint_vel: 0.0
    noise_elevation_map: 0.0

    # 加载模型后是否暂停
    unPauseService: "/unpause_mujoco" # 启动服务名称
    initPauseFlag: false # 1是会暂停,0是不会暂停

    # 是否输出模型信息表格
    modelTableFlag: false # 1是会,0是不会

    # 是否输出log信息（lidar和IMU高度信息）
    enableLogOutput: false # true是输出,false是不输出

    g_unit: "g" # 重力单位 可选项: g, m/s^2

    pointCloudType: "PointCloud2" # 可选项: PointCloud2, CustomMsg

    elevation_map:
      enabled: true                                           # 设置为 true 来启用此功能
      topic: "/elevation/map_array"                          # 高程图发布的话题
      attach_link_name: "lidar_site"                         # 以哪一个link为基准
      # size: [ 1.55, 1.55 ]                                      # [长, 宽] (米), 对应机器人的前后和左右
      size: [ 1.35, 0.95 ]                                      # [长, 宽] (米), 对应机器人的前后和左右
      resolution: 0.05                                         # 分辨率 (米/格)
      update_rate: 60.0                                       # 更新频率 (Hz)
      debug_info: true                                        # 是否发布调试信息

    # 是否启用激光雷达
    enableLidar: false # true表示启用，false表示禁用
